### ISSUE TITLE
Codegen emits RefreshInternalVisualReferences() call for non-Forms output libraries, breaking compile

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/Gum#3501]
## Problem

Codegen for `InitializeInstances`/`AfterFullCreation` unconditionally emits `base.RefreshInternalVisualReferences();` whenever `ObjectInstantiationType.FullyInCode` is used and the element isn't derived from a code-generated base — for **any** `OutputLibrary` other than `Skia`. But `RefreshInternalVisualReferences` only exists on the Forms hierarchy (`FrameworkElement` and its `MonoGameGum/Forms/Controls/*` subclasses) — it is not defined on plain `GraphicalUiElement`/`ContainerRuntime`.

This breaks compilation of generated code (`CS0117`) for any non-Forms output library — `MonoGame`, `Raylib`, `WPF`, `Maui`, `XamarinForms` — when using fully-in-code instantiation, e.g.:

```
MainMenuRuntime.Generated.cs(49,14): Error CS0117 : 'GraphicalUiElement' does not contain a definition for 'RefreshInternalVisualReferences'
ScrollBarRuntime.Generated.cs(166,14): Error CS0117 : 'ContainerRuntime' does not contain a definition for 'RefreshInternalVisualReferences'
IconRuntime.Generated.cs(650,14): Error CS0117 : 'ContainerRuntime' does not contain a definition for 'RefreshInternalVisualReferences'
ButtonIconRuntime.Generated.cs(130,14): Error CS0117 : 'ContainerRuntime' does not contain a definition for 'RefreshInternalVisualReferences'
ButtonStandardRuntime.Generated.cs(133,14): Error CS0117 : 'ContainerRuntime' does not contain a definition for 'RefreshInternalVisualReferences'
ListBoxItemRuntime.Generated.cs(116,14): Error CS0117 : 'ContainerRuntime' does not contain a definition for 'RefreshInternalVisualReferences'
ListBoxRuntime.Generated.cs(124,14): Error CS0117 : 'ContainerRuntime' does not contain a definition for 'RefreshInternalVisualReferences'
```

This is not version-specific — it affects any Gum tool version since the feature was introduced, for any project using non-Forms, non-Skia output with fully-in-code instantiation.

## Suggested improvement

Gate the emission on `OutputLibrary == OutputLibrary.MonoGameForms`, matching the equivalent check a few lines above it (which correctly guards the `ReactToVisualChanged` call the same way).

## Source

`Tools/Gum.ProjectServices/CodeGeneration/CodeGenerator.cs:1378-1383`:

```csharp
if(isFullyInstantiatingInCode && !isDerived && context.CodeOutputProjectSettings.OutputLibrary != OutputLibrary.Skia)
{
    //RefreshInternalVisualReferences
    context.StringBuilder.AppendLine(context.Tabs + "base.RefreshInternalVisualReferences();");
}
```

Introduced in 81bac8c13 (#2328). Compare to the correctly-gated check at line 1308 (`OutputLibrary == OutputLibrary.MonoGameForms`) a few lines above.
